### ISSUE TITLE
The glsdk directory is missing

### ISSUE THREAD

**Issue by Accelerator17** [paroj/gltut#127]

**Comment by mradionov** [comment]
glsdk itself is available here - https://sourceforge.net/projects/glsdk/files/ - but I wasn't able to compile any version of it on my Ubuntu. Moreover, I am not sure that it will work anyway, because from what I get the tutorial was distributed with a modified version of glsdk.

The only place where I've found the original tutorial is via Wayback Machine: http://web.archive.org/web/20160406200137/https://bitbucket.org/alfonse/gltut/downloads

It has glsdk in it, which does compile. But unfortunately, the first tutorial itself does not, at least on my system.

Hope it helps someone.

**Comment by paroj** [comment]
fixed with db01d1c5d255a9e819facb9dcfc47cd560b27268
